[project]
name = "companiestextdataexploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=5.24.1",
    "polars>=1.21.0",
    "pyarrow>=19.0.0",
    "streamlit>=1.41.1",
]
